import type { Metadata } from "next";
import SideBar from "@/components/layout/SideBar";
import { Manrope } from "next/font/google";
import "./globals.css";

const manrope = Manrope({
	variable: "--font-manrope",
	subsets: ["latin"],
});
export const metadata: Metadata = {
	title: "Nala",
	description: "Generated by create next app",
	icons: {
		icon: "/Nala-Logo.svg",
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={`${manrope.className} h-full antialiased`}>
			<body className="min-h-full flex flex-row">
				<SideBar/>
				{children}
			</body>
		</html>
	);
}
